ALTER TABLE features
	ADD COLUMN IF NOT EXISTS eval_cache_enabled BOOLEAN NOT NULL DEFAULT FALSE,
	ADD COLUMN IF NOT EXISTS eval_cache_ttl_seconds INTEGER NOT NULL DEFAULT 0;

ALTER TABLE auth_profiles
	ADD COLUMN IF NOT EXISTS cache_enabled BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE segments
	ADD COLUMN IF NOT EXISTS membership_cache_enabled BOOLEAN NOT NULL DEFAULT FALSE,
	ADD COLUMN IF NOT EXISTS membership_cache_ttl_seconds INTEGER NOT NULL DEFAULT 0,
	ADD COLUMN IF NOT EXISTS record_cache_enabled BOOLEAN NOT NULL DEFAULT FALSE,
	ADD COLUMN IF NOT EXISTS record_cache_ttl_seconds INTEGER NOT NULL DEFAULT 0;

ALTER TABLE experiments
	ADD COLUMN IF NOT EXISTS lookup_cache_enabled BOOLEAN NOT NULL DEFAULT FALSE,
	ADD COLUMN IF NOT EXISTS lookup_cache_ttl_seconds INTEGER NOT NULL DEFAULT 0;
