/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthAccessDeniedRouteImport } from './routes/auth/access-denied'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedExperimentsRouteImport } from './routes/_authenticated/experiments'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedSegmentsIndexRouteImport } from './routes/_authenticated/segments/index'
import { Route as AuthenticatedHistoryIndexRouteImport } from './routes/_authenticated/history/index'
import { Route as AuthenticatedFeaturesIndexRouteImport } from './routes/_authenticated/features/index'
import { Route as AuthenticatedExperimentsIndexRouteImport } from './routes/_authenticated/experiments/index'
import { Route as AuthenticatedSettingsWorkspacesRouteImport } from './routes/_authenticated/settings/workspaces'
import { Route as AuthenticatedSettingsSecurityRouteImport } from './routes/_authenticated/settings/security'
import { Route as AuthenticatedSettingsMembersRouteImport } from './routes/_authenticated/settings/members'
import { Route as AuthenticatedSettingsExternalApisRouteImport } from './routes/_authenticated/settings/external-apis'
import { Route as AuthenticatedSettingsAuthProfilesRouteImport } from './routes/_authenticated/settings/auth-profiles'
import { Route as AuthenticatedSettingsApiKeysRouteImport } from './routes/_authenticated/settings/api-keys'
import { Route as AuthenticatedSegmentsSegmentKeyRouteImport } from './routes/_authenticated/segments/$segmentKey'
import { Route as AuthenticatedFeaturesNewRouteImport } from './routes/_authenticated/features/new'
import { Route as AuthenticatedFeaturesFeatureKeyRouteImport } from './routes/_authenticated/features/$featureKey'
import { Route as AuthenticatedExperimentsNewRouteImport } from './routes/_authenticated/experiments/new'
import { Route as AuthenticatedExperimentsExperimentIdRouteImport } from './routes/_authenticated/experiments/$experimentId'
import { Route as AuthenticatedSettingsPacksIndexRouteImport } from './routes/_authenticated/settings/packs/index'
import { Route as AuthenticatedSettingsExternalApisIndexRouteImport } from './routes/_authenticated/settings/external-apis/index'
import { Route as AuthenticatedSettingsAuthProfilesIndexRouteImport } from './routes/_authenticated/settings/auth-profiles/index'
import { Route as AuthenticatedSegmentsSegmentKeyIndexRouteImport } from './routes/_authenticated/segments/$segmentKey/index'
import { Route as AuthenticatedFeaturesFeatureKeyIndexRouteImport } from './routes/_authenticated/features/$featureKey/index'
import { Route as AuthenticatedSettingsPacksPackKeyRouteImport } from './routes/_authenticated/settings/packs/$packKey'
import { Route as AuthenticatedSettingsExternalApisNewRouteImport } from './routes/_authenticated/settings/external-apis/new'
import { Route as AuthenticatedSettingsExternalApisKeyRouteImport } from './routes/_authenticated/settings/external-apis/$key'
import { Route as AuthenticatedSettingsAuthProfilesNewRouteImport } from './routes/_authenticated/settings/auth-profiles/new'
import { Route as AuthenticatedSettingsAuthProfilesKeyRouteImport } from './routes/_authenticated/settings/auth-profiles/$key'
import { Route as AuthenticatedFeaturesFeatureKeyObservabilityRouteImport } from './routes/_authenticated/features/$featureKey/observability'
import { Route as AuthenticatedFeaturesFeatureKeyEditRouteImport } from './routes/_authenticated/features/$featureKey/edit'
import { Route as AuthenticatedSettingsPacksPackKeyIndexRouteImport } from './routes/_authenticated/settings/packs/$packKey/index'
import { Route as AuthenticatedFeaturesFeatureKeyRulesNewRouteImport } from './routes/_authenticated/features/$featureKey/rules/new'
import { Route as AuthenticatedFeaturesFeatureKeyRulesRuleIdEditRouteImport } from './routes/_authenticated/features/$featureKey/rules/$ruleId.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAccessDeniedRoute = AuthAccessDeniedRouteImport.update({
  id: '/auth/access-denied',
  path: '/auth/access-denied',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExperimentsRoute =
  AuthenticatedExperimentsRouteImport.update({
    id: '/experiments',
    path: '/experiments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSegmentsIndexRoute =
  AuthenticatedSegmentsIndexRouteImport.update({
    id: '/segments/',
    path: '/segments/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHistoryIndexRoute =
  AuthenticatedHistoryIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedHistoryRoute,
  } as any)
const AuthenticatedFeaturesIndexRoute =
  AuthenticatedFeaturesIndexRouteImport.update({
    id: '/features/',
    path: '/features/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExperimentsIndexRoute =
  AuthenticatedExperimentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedExperimentsRoute,
  } as any)
const AuthenticatedSettingsWorkspacesRoute =
  AuthenticatedSettingsWorkspacesRouteImport.update({
    id: '/settings/workspaces',
    path: '/settings/workspaces',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsSecurityRoute =
  AuthenticatedSettingsSecurityRouteImport.update({
    id: '/settings/security',
    path: '/settings/security',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsMembersRoute =
  AuthenticatedSettingsMembersRouteImport.update({
    id: '/settings/members',
    path: '/settings/members',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsExternalApisRoute =
  AuthenticatedSettingsExternalApisRouteImport.update({
    id: '/settings/external-apis',
    path: '/settings/external-apis',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsAuthProfilesRoute =
  AuthenticatedSettingsAuthProfilesRouteImport.update({
    id: '/settings/auth-profiles',
    path: '/settings/auth-profiles',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsApiKeysRoute =
  AuthenticatedSettingsApiKeysRouteImport.update({
    id: '/settings/api-keys',
    path: '/settings/api-keys',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSegmentsSegmentKeyRoute =
  AuthenticatedSegmentsSegmentKeyRouteImport.update({
    id: '/segments/$segmentKey',
    path: '/segments/$segmentKey',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFeaturesNewRoute =
  AuthenticatedFeaturesNewRouteImport.update({
    id: '/features/new',
    path: '/features/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFeaturesFeatureKeyRoute =
  AuthenticatedFeaturesFeatureKeyRouteImport.update({
    id: '/features/$featureKey',
    path: '/features/$featureKey',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExperimentsNewRoute =
  AuthenticatedExperimentsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedExperimentsRoute,
  } as any)
const AuthenticatedExperimentsExperimentIdRoute =
  AuthenticatedExperimentsExperimentIdRouteImport.update({
    id: '/$experimentId',
    path: '/$experimentId',
    getParentRoute: () => AuthenticatedExperimentsRoute,
  } as any)
const AuthenticatedSettingsPacksIndexRoute =
  AuthenticatedSettingsPacksIndexRouteImport.update({
    id: '/settings/packs/',
    path: '/settings/packs/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsExternalApisIndexRoute =
  AuthenticatedSettingsExternalApisIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsExternalApisRoute,
  } as any)
const AuthenticatedSettingsAuthProfilesIndexRoute =
  AuthenticatedSettingsAuthProfilesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsAuthProfilesRoute,
  } as any)
const AuthenticatedSegmentsSegmentKeyIndexRoute =
  AuthenticatedSegmentsSegmentKeyIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSegmentsSegmentKeyRoute,
  } as any)
const AuthenticatedFeaturesFeatureKeyIndexRoute =
  AuthenticatedFeaturesFeatureKeyIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedFeaturesFeatureKeyRoute,
  } as any)
const AuthenticatedSettingsPacksPackKeyRoute =
  AuthenticatedSettingsPacksPackKeyRouteImport.update({
    id: '/settings/packs/$packKey',
    path: '/settings/packs/$packKey',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsExternalApisNewRoute =
  AuthenticatedSettingsExternalApisNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedSettingsExternalApisRoute,
  } as any)
const AuthenticatedSettingsExternalApisKeyRoute =
  AuthenticatedSettingsExternalApisKeyRouteImport.update({
    id: '/$key',
    path: '/$key',
    getParentRoute: () => AuthenticatedSettingsExternalApisRoute,
  } as any)
const AuthenticatedSettingsAuthProfilesNewRoute =
  AuthenticatedSettingsAuthProfilesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedSettingsAuthProfilesRoute,
  } as any)
const AuthenticatedSettingsAuthProfilesKeyRoute =
  AuthenticatedSettingsAuthProfilesKeyRouteImport.update({
    id: '/$key',
    path: '/$key',
    getParentRoute: () => AuthenticatedSettingsAuthProfilesRoute,
  } as any)
const AuthenticatedFeaturesFeatureKeyObservabilityRoute =
  AuthenticatedFeaturesFeatureKeyObservabilityRouteImport.update({
    id: '/observability',
    path: '/observability',
    getParentRoute: () => AuthenticatedFeaturesFeatureKeyRoute,
  } as any)
const AuthenticatedFeaturesFeatureKeyEditRoute =
  AuthenticatedFeaturesFeatureKeyEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedFeaturesFeatureKeyRoute,
  } as any)
const AuthenticatedSettingsPacksPackKeyIndexRoute =
  AuthenticatedSettingsPacksPackKeyIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsPacksPackKeyRoute,
  } as any)
const AuthenticatedFeaturesFeatureKeyRulesNewRoute =
  AuthenticatedFeaturesFeatureKeyRulesNewRouteImport.update({
    id: '/rules/new',
    path: '/rules/new',
    getParentRoute: () => AuthenticatedFeaturesFeatureKeyRoute,
  } as any)
const AuthenticatedFeaturesFeatureKeyRulesRuleIdEditRoute =
  AuthenticatedFeaturesFeatureKeyRulesRuleIdEditRouteImport.update({
    id: '/rules/$ruleId/edit',
    path: '/rules/$ruleId/edit',
    getParentRoute: () => AuthenticatedFeaturesFeatureKeyRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/experiments': typeof AuthenticatedExperimentsRouteWithChildren
  '/history': typeof AuthenticatedHistoryRouteWithChildren
  '/auth/access-denied': typeof AuthAccessDeniedRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/experiments/$experimentId': typeof AuthenticatedExperimentsExperimentIdRoute
  '/experiments/new': typeof AuthenticatedExperimentsNewRoute
  '/features/$featureKey': typeof AuthenticatedFeaturesFeatureKeyRouteWithChildren
  '/features/new': typeof AuthenticatedFeaturesNewRoute
  '/segments/$segmentKey': typeof AuthenticatedSegmentsSegmentKeyRouteWithChildren
  '/settings/api-keys': typeof AuthenticatedSettingsApiKeysRoute
  '/settings/auth-profiles': typeof AuthenticatedSettingsAuthProfilesRouteWithChildren
  '/settings/external-apis': typeof AuthenticatedSettingsExternalApisRouteWithChildren
  '/settings/members': typeof AuthenticatedSettingsMembersRoute
  '/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/settings/workspaces': typeof AuthenticatedSettingsWorkspacesRoute
  '/experiments/': typeof AuthenticatedExperimentsIndexRoute
  '/features/': typeof AuthenticatedFeaturesIndexRoute
  '/history/': typeof AuthenticatedHistoryIndexRoute
  '/segments/': typeof AuthenticatedSegmentsIndexRoute
  '/features/$featureKey/edit': typeof AuthenticatedFeaturesFeatureKeyEditRoute
  '/features/$featureKey/observability': typeof AuthenticatedFeaturesFeatureKeyObservabilityRoute
  '/settings/auth-profiles/$key': typeof AuthenticatedSettingsAuthProfilesKeyRoute
  '/settings/auth-profiles/new': typeof AuthenticatedSettingsAuthProfilesNewRoute
  '/settings/external-apis/$key': typeof AuthenticatedSettingsExternalApisKeyRoute
  '/settings/external-apis/new': typeof AuthenticatedSettingsExternalApisNewRoute
  '/settings/packs/$packKey': typeof AuthenticatedSettingsPacksPackKeyRouteWithChildren
  '/features/$featureKey/': typeof AuthenticatedFeaturesFeatureKeyIndexRoute
  '/segments/$segmentKey/': typeof AuthenticatedSegmentsSegmentKeyIndexRoute
  '/settings/auth-profiles/': typeof AuthenticatedSettingsAuthProfilesIndexRoute
  '/settings/external-apis/': typeof AuthenticatedSettingsExternalApisIndexRoute
  '/settings/packs/': typeof AuthenticatedSettingsPacksIndexRoute
  '/features/$featureKey/rules/new': typeof AuthenticatedFeaturesFeatureKeyRulesNewRoute
  '/settings/packs/$packKey/': typeof AuthenticatedSettingsPacksPackKeyIndexRoute
  '/features/$featureKey/rules/$ruleId/edit': typeof AuthenticatedFeaturesFeatureKeyRulesRuleIdEditRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/auth/access-denied': typeof AuthAccessDeniedRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/': typeof AuthenticatedIndexRoute
  '/experiments/$experimentId': typeof AuthenticatedExperimentsExperimentIdRoute
  '/experiments/new': typeof AuthenticatedExperimentsNewRoute
  '/features/new': typeof AuthenticatedFeaturesNewRoute
  '/settings/api-keys': typeof AuthenticatedSettingsApiKeysRoute
  '/settings/members': typeof AuthenticatedSettingsMembersRoute
  '/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/settings/workspaces': typeof AuthenticatedSettingsWorkspacesRoute
  '/experiments': typeof AuthenticatedExperimentsIndexRoute
  '/features': typeof AuthenticatedFeaturesIndexRoute
  '/history': typeof AuthenticatedHistoryIndexRoute
  '/segments': typeof AuthenticatedSegmentsIndexRoute
  '/features/$featureKey/edit': typeof AuthenticatedFeaturesFeatureKeyEditRoute
  '/features/$featureKey/observability': typeof AuthenticatedFeaturesFeatureKeyObservabilityRoute
  '/settings/auth-profiles/$key': typeof AuthenticatedSettingsAuthProfilesKeyRoute
  '/settings/auth-profiles/new': typeof AuthenticatedSettingsAuthProfilesNewRoute
  '/settings/external-apis/$key': typeof AuthenticatedSettingsExternalApisKeyRoute
  '/settings/external-apis/new': typeof AuthenticatedSettingsExternalApisNewRoute
  '/features/$featureKey': typeof AuthenticatedFeaturesFeatureKeyIndexRoute
  '/segments/$segmentKey': typeof AuthenticatedSegmentsSegmentKeyIndexRoute
  '/settings/auth-profiles': typeof AuthenticatedSettingsAuthProfilesIndexRoute
  '/settings/external-apis': typeof AuthenticatedSettingsExternalApisIndexRoute
  '/settings/packs': typeof AuthenticatedSettingsPacksIndexRoute
  '/features/$featureKey/rules/new': typeof AuthenticatedFeaturesFeatureKeyRulesNewRoute
  '/settings/packs/$packKey': typeof AuthenticatedSettingsPacksPackKeyIndexRoute
  '/features/$featureKey/rules/$ruleId/edit': typeof AuthenticatedFeaturesFeatureKeyRulesRuleIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/experiments': typeof AuthenticatedExperimentsRouteWithChildren
  '/_authenticated/history': typeof AuthenticatedHistoryRouteWithChildren
  '/auth/access-denied': typeof AuthAccessDeniedRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/experiments/$experimentId': typeof AuthenticatedExperimentsExperimentIdRoute
  '/_authenticated/experiments/new': typeof AuthenticatedExperimentsNewRoute
  '/_authenticated/features/$featureKey': typeof AuthenticatedFeaturesFeatureKeyRouteWithChildren
  '/_authenticated/features/new': typeof AuthenticatedFeaturesNewRoute
  '/_authenticated/segments/$segmentKey': typeof AuthenticatedSegmentsSegmentKeyRouteWithChildren
  '/_authenticated/settings/api-keys': typeof AuthenticatedSettingsApiKeysRoute
  '/_authenticated/settings/auth-profiles': typeof AuthenticatedSettingsAuthProfilesRouteWithChildren
  '/_authenticated/settings/external-apis': typeof AuthenticatedSettingsExternalApisRouteWithChildren
  '/_authenticated/settings/members': typeof AuthenticatedSettingsMembersRoute
  '/_authenticated/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/_authenticated/settings/workspaces': typeof AuthenticatedSettingsWorkspacesRoute
  '/_authenticated/experiments/': typeof AuthenticatedExperimentsIndexRoute
  '/_authenticated/features/': typeof AuthenticatedFeaturesIndexRoute
  '/_authenticated/history/': typeof AuthenticatedHistoryIndexRoute
  '/_authenticated/segments/': typeof AuthenticatedSegmentsIndexRoute
  '/_authenticated/features/$featureKey/edit': typeof AuthenticatedFeaturesFeatureKeyEditRoute
  '/_authenticated/features/$featureKey/observability': typeof AuthenticatedFeaturesFeatureKeyObservabilityRoute
  '/_authenticated/settings/auth-profiles/$key': typeof AuthenticatedSettingsAuthProfilesKeyRoute
  '/_authenticated/settings/auth-profiles/new': typeof AuthenticatedSettingsAuthProfilesNewRoute
  '/_authenticated/settings/external-apis/$key': typeof AuthenticatedSettingsExternalApisKeyRoute
  '/_authenticated/settings/external-apis/new': typeof AuthenticatedSettingsExternalApisNewRoute
  '/_authenticated/settings/packs/$packKey': typeof AuthenticatedSettingsPacksPackKeyRouteWithChildren
  '/_authenticated/features/$featureKey/': typeof AuthenticatedFeaturesFeatureKeyIndexRoute
  '/_authenticated/segments/$segmentKey/': typeof AuthenticatedSegmentsSegmentKeyIndexRoute
  '/_authenticated/settings/auth-profiles/': typeof AuthenticatedSettingsAuthProfilesIndexRoute
  '/_authenticated/settings/external-apis/': typeof AuthenticatedSettingsExternalApisIndexRoute
  '/_authenticated/settings/packs/': typeof AuthenticatedSettingsPacksIndexRoute
  '/_authenticated/features/$featureKey/rules/new': typeof AuthenticatedFeaturesFeatureKeyRulesNewRoute
  '/_authenticated/settings/packs/$packKey/': typeof AuthenticatedSettingsPacksPackKeyIndexRoute
  '/_authenticated/features/$featureKey/rules/$ruleId/edit': typeof AuthenticatedFeaturesFeatureKeyRulesRuleIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/audit'
    | '/experiments'
    | '/history'
    | '/auth/access-denied'
    | '/auth/callback'
    | '/experiments/$experimentId'
    | '/experiments/new'
    | '/features/$featureKey'
    | '/features/new'
    | '/segments/$segmentKey'
    | '/settings/api-keys'
    | '/settings/auth-profiles'
    | '/settings/external-apis'
    | '/settings/members'
    | '/settings/security'
    | '/settings/workspaces'
    | '/experiments/'
    | '/features/'
    | '/history/'
    | '/segments/'
    | '/features/$featureKey/edit'
    | '/features/$featureKey/observability'
    | '/settings/auth-profiles/$key'
    | '/settings/auth-profiles/new'
    | '/settings/external-apis/$key'
    | '/settings/external-apis/new'
    | '/settings/packs/$packKey'
    | '/features/$featureKey/'
    | '/segments/$segmentKey/'
    | '/settings/auth-profiles/'
    | '/settings/external-apis/'
    | '/settings/packs/'
    | '/features/$featureKey/rules/new'
    | '/settings/packs/$packKey/'
    | '/features/$featureKey/rules/$ruleId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/audit'
    | '/auth/access-denied'
    | '/auth/callback'
    | '/'
    | '/experiments/$experimentId'
    | '/experiments/new'
    | '/features/new'
    | '/settings/api-keys'
    | '/settings/members'
    | '/settings/security'
    | '/settings/workspaces'
    | '/experiments'
    | '/features'
    | '/history'
    | '/segments'
    | '/features/$featureKey/edit'
    | '/features/$featureKey/observability'
    | '/settings/auth-profiles/$key'
    | '/settings/auth-profiles/new'
    | '/settings/external-apis/$key'
    | '/settings/external-apis/new'
    | '/features/$featureKey'
    | '/segments/$segmentKey'
    | '/settings/auth-profiles'
    | '/settings/external-apis'
    | '/settings/packs'
    | '/features/$featureKey/rules/new'
    | '/settings/packs/$packKey'
    | '/features/$featureKey/rules/$ruleId/edit'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/audit'
    | '/_authenticated/experiments'
    | '/_authenticated/history'
    | '/auth/access-denied'
    | '/auth/callback'
    | '/_authenticated/'
    | '/_authenticated/experiments/$experimentId'
    | '/_authenticated/experiments/new'
    | '/_authenticated/features/$featureKey'
    | '/_authenticated/features/new'
    | '/_authenticated/segments/$segmentKey'
    | '/_authenticated/settings/api-keys'
    | '/_authenticated/settings/auth-profiles'
    | '/_authenticated/settings/external-apis'
    | '/_authenticated/settings/members'
    | '/_authenticated/settings/security'
    | '/_authenticated/settings/workspaces'
    | '/_authenticated/experiments/'
    | '/_authenticated/features/'
    | '/_authenticated/history/'
    | '/_authenticated/segments/'
    | '/_authenticated/features/$featureKey/edit'
    | '/_authenticated/features/$featureKey/observability'
    | '/_authenticated/settings/auth-profiles/$key'
    | '/_authenticated/settings/auth-profiles/new'
    | '/_authenticated/settings/external-apis/$key'
    | '/_authenticated/settings/external-apis/new'
    | '/_authenticated/settings/packs/$packKey'
    | '/_authenticated/features/$featureKey/'
    | '/_authenticated/segments/$segmentKey/'
    | '/_authenticated/settings/auth-profiles/'
    | '/_authenticated/settings/external-apis/'
    | '/_authenticated/settings/packs/'
    | '/_authenticated/features/$featureKey/rules/new'
    | '/_authenticated/settings/packs/$packKey/'
    | '/_authenticated/features/$featureKey/rules/$ruleId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthAccessDeniedRoute: typeof AuthAccessDeniedRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/access-denied': {
      id: '/auth/access-denied'
      path: '/auth/access-denied'
      fullPath: '/auth/access-denied'
      preLoaderRoute: typeof AuthAccessDeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/experiments': {
      id: '/_authenticated/experiments'
      path: '/experiments'
      fullPath: '/experiments'
      preLoaderRoute: typeof AuthenticatedExperimentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/segments/': {
      id: '/_authenticated/segments/'
      path: '/segments'
      fullPath: '/segments/'
      preLoaderRoute: typeof AuthenticatedSegmentsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/history/': {
      id: '/_authenticated/history/'
      path: '/'
      fullPath: '/history/'
      preLoaderRoute: typeof AuthenticatedHistoryIndexRouteImport
      parentRoute: typeof AuthenticatedHistoryRoute
    }
    '/_authenticated/features/': {
      id: '/_authenticated/features/'
      path: '/features'
      fullPath: '/features/'
      preLoaderRoute: typeof AuthenticatedFeaturesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/experiments/': {
      id: '/_authenticated/experiments/'
      path: '/'
      fullPath: '/experiments/'
      preLoaderRoute: typeof AuthenticatedExperimentsIndexRouteImport
      parentRoute: typeof AuthenticatedExperimentsRoute
    }
    '/_authenticated/settings/workspaces': {
      id: '/_authenticated/settings/workspaces'
      path: '/settings/workspaces'
      fullPath: '/settings/workspaces'
      preLoaderRoute: typeof AuthenticatedSettingsWorkspacesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/security': {
      id: '/_authenticated/settings/security'
      path: '/settings/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AuthenticatedSettingsSecurityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/members': {
      id: '/_authenticated/settings/members'
      path: '/settings/members'
      fullPath: '/settings/members'
      preLoaderRoute: typeof AuthenticatedSettingsMembersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/external-apis': {
      id: '/_authenticated/settings/external-apis'
      path: '/settings/external-apis'
      fullPath: '/settings/external-apis'
      preLoaderRoute: typeof AuthenticatedSettingsExternalApisRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/auth-profiles': {
      id: '/_authenticated/settings/auth-profiles'
      path: '/settings/auth-profiles'
      fullPath: '/settings/auth-profiles'
      preLoaderRoute: typeof AuthenticatedSettingsAuthProfilesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/api-keys': {
      id: '/_authenticated/settings/api-keys'
      path: '/settings/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof AuthenticatedSettingsApiKeysRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/segments/$segmentKey': {
      id: '/_authenticated/segments/$segmentKey'
      path: '/segments/$segmentKey'
      fullPath: '/segments/$segmentKey'
      preLoaderRoute: typeof AuthenticatedSegmentsSegmentKeyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/features/new': {
      id: '/_authenticated/features/new'
      path: '/features/new'
      fullPath: '/features/new'
      preLoaderRoute: typeof AuthenticatedFeaturesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/features/$featureKey': {
      id: '/_authenticated/features/$featureKey'
      path: '/features/$featureKey'
      fullPath: '/features/$featureKey'
      preLoaderRoute: typeof AuthenticatedFeaturesFeatureKeyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/experiments/new': {
      id: '/_authenticated/experiments/new'
      path: '/new'
      fullPath: '/experiments/new'
      preLoaderRoute: typeof AuthenticatedExperimentsNewRouteImport
      parentRoute: typeof AuthenticatedExperimentsRoute
    }
    '/_authenticated/experiments/$experimentId': {
      id: '/_authenticated/experiments/$experimentId'
      path: '/$experimentId'
      fullPath: '/experiments/$experimentId'
      preLoaderRoute: typeof AuthenticatedExperimentsExperimentIdRouteImport
      parentRoute: typeof AuthenticatedExperimentsRoute
    }
    '/_authenticated/settings/packs/': {
      id: '/_authenticated/settings/packs/'
      path: '/settings/packs'
      fullPath: '/settings/packs/'
      preLoaderRoute: typeof AuthenticatedSettingsPacksIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/external-apis/': {
      id: '/_authenticated/settings/external-apis/'
      path: '/'
      fullPath: '/settings/external-apis/'
      preLoaderRoute: typeof AuthenticatedSettingsExternalApisIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsExternalApisRoute
    }
    '/_authenticated/settings/auth-profiles/': {
      id: '/_authenticated/settings/auth-profiles/'
      path: '/'
      fullPath: '/settings/auth-profiles/'
      preLoaderRoute: typeof AuthenticatedSettingsAuthProfilesIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsAuthProfilesRoute
    }
    '/_authenticated/segments/$segmentKey/': {
      id: '/_authenticated/segments/$segmentKey/'
      path: '/'
      fullPath: '/segments/$segmentKey/'
      preLoaderRoute: typeof AuthenticatedSegmentsSegmentKeyIndexRouteImport
      parentRoute: typeof AuthenticatedSegmentsSegmentKeyRoute
    }
    '/_authenticated/features/$featureKey/': {
      id: '/_authenticated/features/$featureKey/'
      path: '/'
      fullPath: '/features/$featureKey/'
      preLoaderRoute: typeof AuthenticatedFeaturesFeatureKeyIndexRouteImport
      parentRoute: typeof AuthenticatedFeaturesFeatureKeyRoute
    }
    '/_authenticated/settings/packs/$packKey': {
      id: '/_authenticated/settings/packs/$packKey'
      path: '/settings/packs/$packKey'
      fullPath: '/settings/packs/$packKey'
      preLoaderRoute: typeof AuthenticatedSettingsPacksPackKeyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/external-apis/new': {
      id: '/_authenticated/settings/external-apis/new'
      path: '/new'
      fullPath: '/settings/external-apis/new'
      preLoaderRoute: typeof AuthenticatedSettingsExternalApisNewRouteImport
      parentRoute: typeof AuthenticatedSettingsExternalApisRoute
    }
    '/_authenticated/settings/external-apis/$key': {
      id: '/_authenticated/settings/external-apis/$key'
      path: '/$key'
      fullPath: '/settings/external-apis/$key'
      preLoaderRoute: typeof AuthenticatedSettingsExternalApisKeyRouteImport
      parentRoute: typeof AuthenticatedSettingsExternalApisRoute
    }
    '/_authenticated/settings/auth-profiles/new': {
      id: '/_authenticated/settings/auth-profiles/new'
      path: '/new'
      fullPath: '/settings/auth-profiles/new'
      preLoaderRoute: typeof AuthenticatedSettingsAuthProfilesNewRouteImport
      parentRoute: typeof AuthenticatedSettingsAuthProfilesRoute
    }
    '/_authenticated/settings/auth-profiles/$key': {
      id: '/_authenticated/settings/auth-profiles/$key'
      path: '/$key'
      fullPath: '/settings/auth-profiles/$key'
      preLoaderRoute: typeof AuthenticatedSettingsAuthProfilesKeyRouteImport
      parentRoute: typeof AuthenticatedSettingsAuthProfilesRoute
    }
    '/_authenticated/features/$featureKey/observability': {
      id: '/_authenticated/features/$featureKey/observability'
      path: '/observability'
      fullPath: '/features/$featureKey/observability'
      preLoaderRoute: typeof AuthenticatedFeaturesFeatureKeyObservabilityRouteImport
      parentRoute: typeof AuthenticatedFeaturesFeatureKeyRoute
    }
    '/_authenticated/features/$featureKey/edit': {
      id: '/_authenticated/features/$featureKey/edit'
      path: '/edit'
      fullPath: '/features/$featureKey/edit'
      preLoaderRoute: typeof AuthenticatedFeaturesFeatureKeyEditRouteImport
      parentRoute: typeof AuthenticatedFeaturesFeatureKeyRoute
    }
    '/_authenticated/settings/packs/$packKey/': {
      id: '/_authenticated/settings/packs/$packKey/'
      path: '/'
      fullPath: '/settings/packs/$packKey/'
      preLoaderRoute: typeof AuthenticatedSettingsPacksPackKeyIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsPacksPackKeyRoute
    }
    '/_authenticated/features/$featureKey/rules/new': {
      id: '/_authenticated/features/$featureKey/rules/new'
      path: '/rules/new'
      fullPath: '/features/$featureKey/rules/new'
      preLoaderRoute: typeof AuthenticatedFeaturesFeatureKeyRulesNewRouteImport
      parentRoute: typeof AuthenticatedFeaturesFeatureKeyRoute
    }
    '/_authenticated/features/$featureKey/rules/$ruleId/edit': {
      id: '/_authenticated/features/$featureKey/rules/$ruleId/edit'
      path: '/rules/$ruleId/edit'
      fullPath: '/features/$featureKey/rules/$ruleId/edit'
      preLoaderRoute: typeof AuthenticatedFeaturesFeatureKeyRulesRuleIdEditRouteImport
      parentRoute: typeof AuthenticatedFeaturesFeatureKeyRoute
    }
  }
}

interface AuthenticatedExperimentsRouteChildren {
  AuthenticatedExperimentsExperimentIdRoute: typeof AuthenticatedExperimentsExperimentIdRoute
  AuthenticatedExperimentsNewRoute: typeof AuthenticatedExperimentsNewRoute
  AuthenticatedExperimentsIndexRoute: typeof AuthenticatedExperimentsIndexRoute
}

const AuthenticatedExperimentsRouteChildren: AuthenticatedExperimentsRouteChildren =
  {
    AuthenticatedExperimentsExperimentIdRoute:
      AuthenticatedExperimentsExperimentIdRoute,
    AuthenticatedExperimentsNewRoute: AuthenticatedExperimentsNewRoute,
    AuthenticatedExperimentsIndexRoute: AuthenticatedExperimentsIndexRoute,
  }

const AuthenticatedExperimentsRouteWithChildren =
  AuthenticatedExperimentsRoute._addFileChildren(
    AuthenticatedExperimentsRouteChildren,
  )

interface AuthenticatedHistoryRouteChildren {
  AuthenticatedHistoryIndexRoute: typeof AuthenticatedHistoryIndexRoute
}

const AuthenticatedHistoryRouteChildren: AuthenticatedHistoryRouteChildren = {
  AuthenticatedHistoryIndexRoute: AuthenticatedHistoryIndexRoute,
}

const AuthenticatedHistoryRouteWithChildren =
  AuthenticatedHistoryRoute._addFileChildren(AuthenticatedHistoryRouteChildren)

interface AuthenticatedFeaturesFeatureKeyRouteChildren {
  AuthenticatedFeaturesFeatureKeyEditRoute: typeof AuthenticatedFeaturesFeatureKeyEditRoute
  AuthenticatedFeaturesFeatureKeyObservabilityRoute: typeof AuthenticatedFeaturesFeatureKeyObservabilityRoute
  AuthenticatedFeaturesFeatureKeyIndexRoute: typeof AuthenticatedFeaturesFeatureKeyIndexRoute
  AuthenticatedFeaturesFeatureKeyRulesNewRoute: typeof AuthenticatedFeaturesFeatureKeyRulesNewRoute
  AuthenticatedFeaturesFeatureKeyRulesRuleIdEditRoute: typeof AuthenticatedFeaturesFeatureKeyRulesRuleIdEditRoute
}

const AuthenticatedFeaturesFeatureKeyRouteChildren: AuthenticatedFeaturesFeatureKeyRouteChildren =
  {
    AuthenticatedFeaturesFeatureKeyEditRoute:
      AuthenticatedFeaturesFeatureKeyEditRoute,
    AuthenticatedFeaturesFeatureKeyObservabilityRoute:
      AuthenticatedFeaturesFeatureKeyObservabilityRoute,
    AuthenticatedFeaturesFeatureKeyIndexRoute:
      AuthenticatedFeaturesFeatureKeyIndexRoute,
    AuthenticatedFeaturesFeatureKeyRulesNewRoute:
      AuthenticatedFeaturesFeatureKeyRulesNewRoute,
    AuthenticatedFeaturesFeatureKeyRulesRuleIdEditRoute:
      AuthenticatedFeaturesFeatureKeyRulesRuleIdEditRoute,
  }

const AuthenticatedFeaturesFeatureKeyRouteWithChildren =
  AuthenticatedFeaturesFeatureKeyRoute._addFileChildren(
    AuthenticatedFeaturesFeatureKeyRouteChildren,
  )

interface AuthenticatedSegmentsSegmentKeyRouteChildren {
  AuthenticatedSegmentsSegmentKeyIndexRoute: typeof AuthenticatedSegmentsSegmentKeyIndexRoute
}

const AuthenticatedSegmentsSegmentKeyRouteChildren: AuthenticatedSegmentsSegmentKeyRouteChildren =
  {
    AuthenticatedSegmentsSegmentKeyIndexRoute:
      AuthenticatedSegmentsSegmentKeyIndexRoute,
  }

const AuthenticatedSegmentsSegmentKeyRouteWithChildren =
  AuthenticatedSegmentsSegmentKeyRoute._addFileChildren(
    AuthenticatedSegmentsSegmentKeyRouteChildren,
  )

interface AuthenticatedSettingsAuthProfilesRouteChildren {
  AuthenticatedSettingsAuthProfilesKeyRoute: typeof AuthenticatedSettingsAuthProfilesKeyRoute
  AuthenticatedSettingsAuthProfilesNewRoute: typeof AuthenticatedSettingsAuthProfilesNewRoute
  AuthenticatedSettingsAuthProfilesIndexRoute: typeof AuthenticatedSettingsAuthProfilesIndexRoute
}

const AuthenticatedSettingsAuthProfilesRouteChildren: AuthenticatedSettingsAuthProfilesRouteChildren =
  {
    AuthenticatedSettingsAuthProfilesKeyRoute:
      AuthenticatedSettingsAuthProfilesKeyRoute,
    AuthenticatedSettingsAuthProfilesNewRoute:
      AuthenticatedSettingsAuthProfilesNewRoute,
    AuthenticatedSettingsAuthProfilesIndexRoute:
      AuthenticatedSettingsAuthProfilesIndexRoute,
  }

const AuthenticatedSettingsAuthProfilesRouteWithChildren =
  AuthenticatedSettingsAuthProfilesRoute._addFileChildren(
    AuthenticatedSettingsAuthProfilesRouteChildren,
  )

interface AuthenticatedSettingsExternalApisRouteChildren {
  AuthenticatedSettingsExternalApisKeyRoute: typeof AuthenticatedSettingsExternalApisKeyRoute
  AuthenticatedSettingsExternalApisNewRoute: typeof AuthenticatedSettingsExternalApisNewRoute
  AuthenticatedSettingsExternalApisIndexRoute: typeof AuthenticatedSettingsExternalApisIndexRoute
}

const AuthenticatedSettingsExternalApisRouteChildren: AuthenticatedSettingsExternalApisRouteChildren =
  {
    AuthenticatedSettingsExternalApisKeyRoute:
      AuthenticatedSettingsExternalApisKeyRoute,
    AuthenticatedSettingsExternalApisNewRoute:
      AuthenticatedSettingsExternalApisNewRoute,
    AuthenticatedSettingsExternalApisIndexRoute:
      AuthenticatedSettingsExternalApisIndexRoute,
  }

const AuthenticatedSettingsExternalApisRouteWithChildren =
  AuthenticatedSettingsExternalApisRoute._addFileChildren(
    AuthenticatedSettingsExternalApisRouteChildren,
  )

interface AuthenticatedSettingsPacksPackKeyRouteChildren {
  AuthenticatedSettingsPacksPackKeyIndexRoute: typeof AuthenticatedSettingsPacksPackKeyIndexRoute
}

const AuthenticatedSettingsPacksPackKeyRouteChildren: AuthenticatedSettingsPacksPackKeyRouteChildren =
  {
    AuthenticatedSettingsPacksPackKeyIndexRoute:
      AuthenticatedSettingsPacksPackKeyIndexRoute,
  }

const AuthenticatedSettingsPacksPackKeyRouteWithChildren =
  AuthenticatedSettingsPacksPackKeyRoute._addFileChildren(
    AuthenticatedSettingsPacksPackKeyRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedExperimentsRoute: typeof AuthenticatedExperimentsRouteWithChildren
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedFeaturesFeatureKeyRoute: typeof AuthenticatedFeaturesFeatureKeyRouteWithChildren
  AuthenticatedFeaturesNewRoute: typeof AuthenticatedFeaturesNewRoute
  AuthenticatedSegmentsSegmentKeyRoute: typeof AuthenticatedSegmentsSegmentKeyRouteWithChildren
  AuthenticatedSettingsApiKeysRoute: typeof AuthenticatedSettingsApiKeysRoute
  AuthenticatedSettingsAuthProfilesRoute: typeof AuthenticatedSettingsAuthProfilesRouteWithChildren
  AuthenticatedSettingsExternalApisRoute: typeof AuthenticatedSettingsExternalApisRouteWithChildren
  AuthenticatedSettingsMembersRoute: typeof AuthenticatedSettingsMembersRoute
  AuthenticatedSettingsSecurityRoute: typeof AuthenticatedSettingsSecurityRoute
  AuthenticatedSettingsWorkspacesRoute: typeof AuthenticatedSettingsWorkspacesRoute
  AuthenticatedFeaturesIndexRoute: typeof AuthenticatedFeaturesIndexRoute
  AuthenticatedSegmentsIndexRoute: typeof AuthenticatedSegmentsIndexRoute
  AuthenticatedSettingsPacksPackKeyRoute: typeof AuthenticatedSettingsPacksPackKeyRouteWithChildren
  AuthenticatedSettingsPacksIndexRoute: typeof AuthenticatedSettingsPacksIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedExperimentsRoute: AuthenticatedExperimentsRouteWithChildren,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedFeaturesFeatureKeyRoute:
    AuthenticatedFeaturesFeatureKeyRouteWithChildren,
  AuthenticatedFeaturesNewRoute: AuthenticatedFeaturesNewRoute,
  AuthenticatedSegmentsSegmentKeyRoute:
    AuthenticatedSegmentsSegmentKeyRouteWithChildren,
  AuthenticatedSettingsApiKeysRoute: AuthenticatedSettingsApiKeysRoute,
  AuthenticatedSettingsAuthProfilesRoute:
    AuthenticatedSettingsAuthProfilesRouteWithChildren,
  AuthenticatedSettingsExternalApisRoute:
    AuthenticatedSettingsExternalApisRouteWithChildren,
  AuthenticatedSettingsMembersRoute: AuthenticatedSettingsMembersRoute,
  AuthenticatedSettingsSecurityRoute: AuthenticatedSettingsSecurityRoute,
  AuthenticatedSettingsWorkspacesRoute: AuthenticatedSettingsWorkspacesRoute,
  AuthenticatedFeaturesIndexRoute: AuthenticatedFeaturesIndexRoute,
  AuthenticatedSegmentsIndexRoute: AuthenticatedSegmentsIndexRoute,
  AuthenticatedSettingsPacksPackKeyRoute:
    AuthenticatedSettingsPacksPackKeyRouteWithChildren,
  AuthenticatedSettingsPacksIndexRoute: AuthenticatedSettingsPacksIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthAccessDeniedRoute: AuthAccessDeniedRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
